src/beans/Comment.java
package beans;
//コメントそのもの

import java.io.Serializable;//beanの永続化（必要に応じて保存したり復元したり）
import java.util.Date;

public class Comment implements Serializable {
	private static final long serialVersionUID = 1L;

	private int id;//コメントそのものを特定するID
	private int message_id;//投稿を特定するID（どの投稿に対してのコメントなのか）
	private int user_id;//コメントした人のID
	private String comment;//コメント本文
	private Date createdDate;//コメントした日付
	private Date updatedDate;
	private String name;

	//beansの中
	//メッセージの表示機能
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getMessageId() {
		return message_id;
	}

	public void setMessageId(int message_id) {
		this.message_id = message_id;
	}

	public int getUserId() {
		return user_id;
	}

	public void setUserId(int user_id) {
		this.user_id = user_id;
	}

	public String[] getComment() {
		String[] getComment = comment.split("\r\n");
		return getComment;
	}

	public String getCommentStr() {
		return comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}

src/beans/User.java
package beans;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
	private static final long serialVersionUID = 1L;

	private int id;//データベース上のID
	private String login_id;//ログイン時に使用するID（ログインしているユーザーのID）
	private String name;
	private String password;
	private String checkPassword;
	private int department_id;//役職ID
	private int branch_id;//支店ID
	private String department_name;//役職名
	private String branch_name;//支店名
	private int stop;
	private Date createdDate;
	private Date updatedDate;


	//beansの中
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLoginId() {
		return login_id;
	}

	public void setLoginId(String login_id) {
		this.login_id = login_id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getUpdatedDate() {
		return updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	public int getDepartmentId() {
		return department_id;
	}

	public void setDepartmentId(int department_id) {
		this.department_id = department_id;
	}

	public int getBranchId() {
		return branch_id;
	}

	public void setBranchId(int branch_id) {
		this.branch_id = branch_id;
	}

	public String getBranchName() {
		return branch_name;
	}

	public void setBranchName(String branch_name) {
		this.branch_name = branch_name;
	}

	public String getDepartmentName() {
		return department_name;
	}

	public void setDepartmentName(String department_name) {
		this.department_name = department_name;
	}

	public int getStop() {
		return stop;
	}
	public void setStop(int isStop) {
		this.stop = isStop;
	}

	public String getCheckPassword() {
		return checkPassword;
	}

	public void setCheckPassword(String checkPassword) {
		this.checkPassword = checkPassword;
	}

}

src/controller/LoginServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import beans.User;
import service.LoginService;

@WebServlet(urlPatterns = { "/login" })
public class LoginServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		request.getRequestDispatcher("login.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		//jspで入力された情報を引数として取ってきている
		//引数は関数へ受け渡す値を引数(材料）
		String login_id = request.getParameter("login_id");
		String password = request.getParameter("password");

		LoginService loginService = new LoginService();
		//loginServiceのloginメソッドに飛んでいる
		User user = loginService.login(login_id, password);

		HttpSession session = request.getSession();//セッション開始
		if (user != null) {

			session.setAttribute("loginUser", user);
			response.sendRedirect("./");
		} else {

			List<String> messages = new ArrayList<String>();
			messages.add("ログインに失敗しました。");
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("login");
		}
	}

}

src/controller/ManagementServlet.java
package controller;//ユーザー管理画面

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import beans.User;
import service.UserService;

@WebServlet(urlPatterns = { "/management" })
public class ManagementServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request, //入力値は無かったから
			HttpServletResponse response) throws ServletException, IOException {

		HttpSession session = request.getSession();
		User loginUser = new User();
		loginUser = (User) session.getAttribute("loginUser");

		//ログインユーザーの支店が001（本社）以外の場合
		//部署が001以外の場合
		if (!(loginUser.getBranchId() == 1 && loginUser.getDepartmentId() == 1)) {

			List<String> error = new ArrayList<String>();
			error.add("該当権限を持っていないので開けません");
			session.setAttribute("error", error);
			response.sendRedirect("./");//top画面に跳ぶ

		} else {
			//値を保存
			List<User> users = new UserService().getUsers();
			request.setAttribute("users", users);
			request.getRequestDispatcher("/management.jsp").forward(request, response);//配送の支持を行うクラス

		}
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws IOException, ServletException {

		if (request.getParameter("userStop").equals("1")) {//文字列同士を比較する equals
			new UserService().stop(Integer.parseInt(request.getParameter("id")));
		} else {
			new UserService().revival(Integer.parseInt(request.getParameter("id")));
		}

		response.sendRedirect("management");

	}

}

src/controller/NewMessageServlet.java
package controller;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.Message;
import beans.User;
import service.MessageService;

@WebServlet(urlPatterns = { "/newMessage" })
public class NewMessageServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		//jspの名前に合わせる
		request.getRequestDispatcher("NewMessage.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		HttpSession session = request.getSession();

		List<String> messages = new ArrayList<String>();

		if (isValid(request, (messages)) == true) {

			//引数loginUserで指定したオブジェクトを取得する。
			User user = (User) session.getAttribute("loginUser");

			Message message = new Message();
			message.setCategory(request.getParameter("category"));
			message.setSubject(request.getParameter("subject"));
			message.setText(request.getParameter("text"));
			message.setUserId(user.getId());

			//register =登録する
			new MessageService().newMessage(message);

			response.sendRedirect("./");//正しく投稿できたらトップ画面に戻る
		} else {
			session.setAttribute("errorMessages", messages);//エラーメッセージが表示され、
			response.sendRedirect("newMessage");//エラーになれば投稿画面のまま
		}
	}

	private boolean isValid(HttpServletRequest request, List<String> messages) {
		String subject = request.getParameter("subject");
		String category = request.getParameter("category");
		String text = request.getParameter("text");

		//エラーメッセージの表示
		//isEmpty =対象の文字列が空文字列なのかを判定することができる

		if (StringUtils.isEmpty(subject) == true) {
			messages.add("件名を入力してください");
		}
		if (StringUtils.isEmpty(category) == true) {
			messages.add("カテゴリーを入力してください");
		}
		if (StringUtils.isEmpty(text) == true) {
			messages.add("本文を入力してください");
		}
		if (30 < subject.length()) {
			messages.add("件名は30文字以下で入力してください");
		}
		if (10 < category.length()) {
			messages.add("カテゴリーは10文字以下で入力してください");
		}
		if (1000 < text.length()) {
			messages.add("本文は1000文字以下で入力してください");
		}

		//要素が０ならtrueを返す
		if ((messages.size()) == 0) {
			return true;
		} else {
			return false;
		}
	}

}

src/controller/SettingsServlet.java
package controller;//ユーザー編集画面

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.User;
import exception.NoRowsUpdatedRuntimeException;
import service.UserService;

@WebServlet(urlPatterns = { "/settings" })
public class SettingsServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override //このページの中身
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		int id = Integer.parseInt(request.getParameter("id"));//URLの ?=...
		User editUser = new UserService().getUser(id);//1つだけ取って来たいからList型ではなくUser型
		request.setAttribute("editUser", editUser);

		//移動先("settings.jsp")
		request.getRequestDispatcher("settings.jsp").forward(request, response);
	}

	@Override //このページで何をするか
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws ServletException, IOException {

		//エラーメッセージを表示する変数
		List<String> settings = new ArrayList<String>();

		HttpSession session = request.getSession();
		User user = new User();
		user.setLoginId((request.getParameter("login_id")));
		user.setPassword(request.getParameter("password1"));
		user.setName(request.getParameter("name"));
		user.setDepartmentId(Integer.parseInt(request.getParameter("department_id")));
		user.setBranchId(Integer.parseInt(request.getParameter("branch_id")));//支店名
		user.setId(Integer.parseInt(request.getParameter("id")));

		if (isValid(request, settings) == true) {

			try {
				new UserService().update(user);
				response.sendRedirect("management");//編集画面に戻る
			} catch (NoRowsUpdatedRuntimeException e) {
				//settings.add("他の人によって更新されています。最新のデータを表示しました。データを確認してください。");
				session.setAttribute("errorMessages", settings);
				request.setAttribute("editUser", user);
				request.getRequestDispatcher("settings.jsp").forward(request, response);
				return;
			}
		} else {
			session.setAttribute("errorMessages", settings);
			request.setAttribute("editUser", user);
			request.getRequestDispatcher("settings.jsp").forward(request, response);
		}
	}

	//エラー時の表示コメント
	private boolean isValid(HttpServletRequest request, List<String> settings) {

		String name = request.getParameter("name");
		String login_id = request.getParameter("login_id");
		String password1 = request.getParameter("password1");
		String password2 = request.getParameter("password2");//passwordが一致しているか確認

		if (StringUtils.isEmpty(name) == true) {
			settings.add("ユーザー名を入力してください");
		}
		if (10 < name.length()) {
			settings.add("ユーザー名は10文字以下で入力してください");
		}
		if (StringUtils.isEmpty(login_id) == true) {
			settings.add("ログインIDを入力してください");
		}
		if (login_id.matches("^.{6,20}$")== false) {
			settings.add("ログインIDは6文字以上20文字以下で入力してください");
		}
		if (login_id.matches("^[0-9a-zA-Z]+$") == false) {
			settings.add("ログインIDは半角英数字で入力してください");
		}

		if (!(StringUtils.isEmpty(password1) || StringUtils.isEmpty(password2))) {//1と2どちらかが空白でなければ

			if (StringUtils.isEmpty(password1) == true) {
				settings.add("パスワードを入力してください");
			}
			if (StringUtils.isEmpty(password2) == true) {
				settings.add("確認のためもう一度パスワードを入力してください");
			}
			if (password1.equals(password2) != true) {
				settings.add("パスワードが一致しません");
			}
		}

		// TODO アカウントが既に利用されていないか、メールアドレスが既に登録されていないかなどの確認も必要
		if (settings.size() == 0) {
			return true;
		} else {
			return false;
		}
	}
}

src/controller/SignUpServlet.java
package controller;//ユーザー新規登録

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang.StringUtils;

import beans.User;
import service.UserService;

@WebServlet(urlPatterns = { "/signup" })
public class SignUpServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	@Override
	protected void doGet(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		request.getRequestDispatcher("signup.jsp").forward(request, response);
	}

	@Override
	protected void doPost(HttpServletRequest request,
			HttpServletResponse response) throws IOException, ServletException {

		List<String> messages = new ArrayList<String>();

		HttpSession session = request.getSession();
		if (isValid(request, messages) == true) {

			//変数userに下の情報をまとめて入れる
			User user = new User();
			//jspで入力された情報をbeanのlogin_idに入れる
			user.setLoginId(request.getParameter("login_id"));
			user.setName(request.getParameter("name"));
			user.setPassword(request.getParameter("password1"));
			user.setCheckPassword(request.getParameter("password2"));
			user.setBranchId(Integer.parseInt(request.getParameter("branch_id")));
			user.setDepartmentId(Integer.parseInt(request.getParameter("department_id")));

			new UserService().register(user);//登録する

			response.sendRedirect("login");//成功したらログイン画面に遷移する
		} else {
			session.setAttribute("errorMessages", messages);
			response.sendRedirect("signup");//エラーになれば編集画面のまま
		}
	}

	private boolean isValid(HttpServletRequest request, List<String> messages) {
		String login_id = request.getParameter("login_id");
		String name = request.getParameter("name");
		String password1 = request.getParameter("password1");
		String password2 = request.getParameter("password2");

		if (StringUtils.isEmpty(name) == true) {
			messages.add("ユーザー名を入力してください");
		}
		if (10 < name.length()) {
			messages.add("ユーザー名は10文字以下で入力してください");
		}
		if (StringUtils.isEmpty(login_id) == true) {
			messages.add("ログインIDを入力してください");
		}
		if (login_id == "^\\d{6,20}$" == false) {
			messages.add("ログインIDは6文字以上20文字以下で入力してください");
		}
		if ((login_id == "^[0-9a-zA-Z]+$") == false) {
			messages.add("ログインIDは半角英数字で入力してください");
		}
		if (StringUtils.isEmpty(password1) || (password2) == null) {
			messages.add("パスワードを入力してください");
		} else {

			if (StringUtils.isEmpty(password1) == true) {
				messages.add("パスワードを入力してください");
			}
			if (StringUtils.isEmpty(password2) == true) {
				messages.add("確認のためもう一度パスワードを入力してください");
			}
			if (password1.equals(password2) != true) {
				messages.add("パスワードが一致しません");
			}
			if ((password1 == "^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[!-/:-@[-`{-~])[!-~]$") == true) {
				messages.add("パスワードは記号を含む全ての半角文字で入力してください");
			}
			if (password1.length() <= 6 && password1.length() >= 20) {
				messages.add("パスワードは6文字以上20文字以下で入力してください");
			}
			if (password2.length() <= 6 && password2.length() >= 20) {
				messages.add("パスワードは6文字以上20文字以下で入力してください");
			}
		}
		// TODO アカウントが既に利用されていないか、メールアドレスが既に登録されていないかなどの確認も必要
		if (messages.size() == 0) {
			return true;
		} else {
			return false;
		}
	}

}

WebContent/NewMessage.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<title>新規投稿画面</title>
</head>

<!-- <div class="header">

</div> -->

<body>
新規投稿
<br />
<br />
            <!-- エラーメッセージの表示 -->
            <c:if test="${ not empty errorMessages }">
                <div class="errorMessages">
                    <ul>
                        <c:forEach items="${errorMessages}" var="message">
                            <li><c:out value="${message}" />
                        </c:forEach>
                    </ul>
                </div>
                <c:remove var="errorMessages" scope="session"/>
            </c:if><br />

<div style="padding: 10px; margin-bottom: 10px; border: 5px double #333333; border-radius: 10px;">

	<div class="form-area">
		<form action="newMessage" method="post">
			カテゴリー<br />
			<input maxlength='10'name="category" >

			<br /> 件名<br />
			<input maxlength='30' name="subject" >

			<br /> 本文（1000文字まで） <br />
			<textarea name="text" cols="100" rows="5"></textarea>
			<br />

			<!-- ↓新規投稿ボタン -->
			<input type="submit" value="投稿する">

		</form>
	</div>
</div>
	<br />
	<br />
	<a href="./">戻る</a>


	<div class="copyright">Copyright(c)Fukushima Momoko</div>
	<br />
</body>
</html>

WebContent/management.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset="UTF-8">
<title>ユーザー管理</title>
</head>
<body>
	ユーザー管理<br />	<br />
	<div class="main-contents">

		<%--リンクの遷移先のURLはsignup  --%>
		<a href="signup">ユーザー新規登録</a><br /> <br />


		<table class="table1" border=1 >
			<tr>
				<th>ユーザー名</th>
				<th>支店</th>
				<th>部署･役職</th>
				<th>編集</th>
				<th>停止/復活</th>


				<c:forEach items="${users}" var="user">
					<!-- ↓中身はひとつひとつc:outする-->
					<tr>
						<!-- beanの中のget以降の名前の頭文字を小文字にした名前 -->
						<td align="center"><c:out value="${user.name}" /></td>
						<td align="center"><c:out value="${user.branchName}" /></td>
						<td align="center"><c:out value="${user.departmentName}" /></td>


						<%--リンクの遷移先のURLは  --%>
						<td><a href="settings?id=${user.id}">編集</a>
						<!-- INPUT = <form>タグで作成したフォームの中でテキスト入力欄やボタンなどの部品を作成する要素 -->

						<td  align="center">
						<input name="id" value="${editUser.id}" id="id" type="hidden"/>

							<c:if test="${user.stop == 1}">
							<form action="management" method="post">
							    <input type="hidden" name="id" value="${user.id}">
							    <input type="hidden" name="userStop" value="${user.stop}">
								<input type="submit" value="停止" onclick="return disp();">
							</form>
							</c:if>

							<c:if test="${user.stop == 0}">
							<form action="management" method="post">
							    <input type="hidden" name="id" value="${user.id}">
							    <input type="hidden" name="userStop" value="${user.stop}">
							    <!-- value = 何の情報を送るか -->
								<input type="submit" value="復活" onclick="return revival();">
							</form>
							</c:if>


							<script>
							function disp(){
								// 「OK」時の処理開始 ＋ 確認ダイアログの表示
								if(window.confirm('ユーザーを停止しますか？')){
									window.location.href = "/management"; // /managament へジャンプ
								}
								// 「OK」時の処理終了

								// 「キャンセル」時の処理開始
								else{
									window.alert('キャンセルされました'); // 警告ダイアログを表示
									return false;
								}
								// 「キャンセル」時の処理終了
							}
							</script>

							<script>
							function revival(){

								// 「OK」時の処理開始 ＋ 確認ダイアログの表示
								if(window.confirm('ユーザーを復活させますか？')){
									window.location.href = "/management"; // /managament へジャンプ
								}
								// 「OK」時の処理終了

								// 「キャンセル」時の処理開始
								else{
									window.alert('キャンセルされました'); // 警告ダイアログを表示
									return false;
								}
								// 「キャンセル」時の処理終了
							}
							</script>

					</tr>
				</c:forEach>
		    </table>


		<br /> <a href="./">戻る</a>

		<div class="copyright">Copyright(c)Fukushima Momoko</div>
	</div>
</body>
</html>

WebContent/top.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@page isELIgnored="false"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>掲示板システム</title>
<style>
<link href="./css/style.css" rel="stylesheet" type="text/css">
</style>
</head>

<body>
	<div class="header">
		<div class="main-contents">
			<%-- ↓ログインしてないユーザー empty =空の --%>
			<!-- エラーメッセージを表示させる-->
			<c:if test="${ empty loginUser }">
				<a href="login">ログイン</a>
			</c:if>
		</div>

		<%-- ↓ログインしているユーザー  not empty =空ではない --%>
			<c:out value="${error}" /><br />
			<c:remove var="error" scope="session"/>

		<%--リンクの遷移先のURLはsettings  --%>
		<a href="management">ユーザー管理</a>

		<%--リンクの遷移先のURLは newMessage  --%>
		<a href="newMessage">新規投稿</a>

		<%--リンクの遷移先のURLはlogout  --%>
		<a href="logout">ログアウト</a><br />
		<br />

		<%-- ログインユーザーの情報を表示させるためのコード --%>
		<div class="user">
			ログイン中：
			<c:out value="${loginUser.name}" /><br /><br /><br />
		</div>
	</div>

    <form method="get" action="./" target="_self">
    <!-- _self = 現在のウィンドウに開く-->

    ↓カテゴリー検索<br />
    <input type="text" name="search" size="31" maxlength="255">
    <!-- name = servlet内の名前と一致させる-->
    <input type="hidden" name="search" value="${category.category}">
    <input type="submit" name="search" value="検索"><br />


    ↓投稿日（期間指定）<br />
    <input type="date" name="start_date" value="" />

    ～<input type="date" name="end_date" value="" />

    <input type="submit" name="date_search" value="絞込み"><br /><br />

    </form><br />



	<%-- 投稿を表示するためのコード --%>
	<div class="messages">
		<%-- ↓c:forEachでfor文で回す --%>
		<%-- var = ${}内の名前と繋がる（同じ） --%>

		<c:forEach items="${messages}" var="message">


			<div style="padding: 10px; margin-bottom: 10px; border: 5px double #333333; border-radius: 10px;">
				<div class="message"><br />


						<%-- <c:out> =表示させる --%>
					<c:forEach items="${users}" var="user">
						<c:if test="${user.id == message.userId}">
							<c:out value="${user.name}" />さん -
						<fmt:formatDate value="${message.createdDate}"
							pattern="yyyy/MM/dd HH:mm:ss" />
						</c:if>
					</c:forEach><br /><br />

                    <div class="category">
						カテゴリー：
						<c:out value="${message.category}" />
						<br />
					</div>
				    <div class="subject">
						件名：
						<c:out value="${message.subject}" />
						<br />
				    </div>

					<div class="text">
						<c:forEach items="${message.text}" var="text">
						  <c:out value="${text}" /><br />
					    </c:forEach>
						<br />
					</div>

					<form action="delete" method="post">
						<input type="hidden" name="message_id" value="${message.id}">
						<input type="submit" value="投稿削除"><br />
						<br />
					</form>
				</div>


				<!-- コメント表示 -->
				<div class="comments">
					<c:forEach items="${comments}" var="comment">
						<div class="comment">


							<%-- <c:if test=>でifの条件指定 投稿IDとコメントIDが一致していたら表示する--%>
							<c:if test="${message.id == comment.messageId}"><br />

                               <div class="comment-user">
									<!-- items = 繰り返し処理の対象となる集合（配列、Mapなど）を指定する。 -->
									<c:forEach items="${users}" var="user">
										<c:if test="${user.id == comment.userId}">
							        <c:out value="${user.name}" />さん -
									<fmt:formatDate value="${comment.createdDate}"
										pattern="yyyy/MM/dd HH:mm:ss" />
							            </c:if>
									</c:forEach>
								</div>



                            <div class="comment">
							<div style="padding: 10px; margin-bottom: 10px; border: 1px solid #333333;
							      border-radius: 10px; background-color: #ffff99;">

							      <c:forEach items="${comment.comment}" var="commentText">
									<c:out value="${commentText}" /><br />
								  </c:forEach>
							 </div>
							</div>



							<form action="deleteComment" method="post">
								    <input type="hidden" name="comment_id" value="${comment.id}">
									<input type="submit" value="↑コメント削除">
								    </form>
							</c:if>
						</div>
					</c:forEach>

					<!-- ↓コメント入力フォーム -->
					<div class="form-area">
						<form action="comment" method="post">
							<input type="hidden" name="message_id" value="${message.id}"><br />
							↑コメント（500文字まで） <br />
							<textarea name="comment" cols="100" rows="3" wrap="hard"></textarea>
							<br /> <input type="submit" value="コメントする"><br />
							<br />
						</form>
					</div>
				</div>
			</div>
		</c:forEach>
	</div>
	<br />
	<a href="./">戻る</a>
	<br />
	<div class="copyright">Copyright(c)Fukushima Momoko</div>
</body>
</html>